name: Hello World Workflow

on:
  workflow_call:  # <- allows other workflows to call this

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"

