name: Reusable DevOps Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: echo "Running in ${{ inputs.environment }} environment"
