name: Hello World Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: |
          echo "Hello World"
          echo "Running in environment: ${{ inputs.environment }}"
